//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imob.View.AluguelController {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AluguelController.IAluguelController")]
    public interface IAluguelController {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAluguelController/Salvar", ReplyAction="http://tempuri.org/IAluguelController/SalvarResponse")]
        Imob.Site.Models.Rent Salvar(Imob.Site.Models.Rent obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAluguelController/Salvar", ReplyAction="http://tempuri.org/IAluguelController/SalvarResponse")]
        System.Threading.Tasks.Task<Imob.Site.Models.Rent> SalvarAsync(Imob.Site.Models.Rent obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAluguelController/Obter", ReplyAction="http://tempuri.org/IAluguelController/ObterResponse")]
        Imob.Site.Models.Rent[] Obter();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAluguelController/Obter", ReplyAction="http://tempuri.org/IAluguelController/ObterResponse")]
        System.Threading.Tasks.Task<Imob.Site.Models.Rent[]> ObterAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAluguelController/ObterIdEInquilinos", ReplyAction="http://tempuri.org/IAluguelController/ObterIdEInquilinosResponse")]
        string[] ObterIdEInquilinos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAluguelController/ObterIdEInquilinos", ReplyAction="http://tempuri.org/IAluguelController/ObterIdEInquilinosResponse")]
        System.Threading.Tasks.Task<string[]> ObterIdEInquilinosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAluguelController/Editar", ReplyAction="http://tempuri.org/IAluguelController/EditarResponse")]
        Imob.Site.Models.Rent Editar(Imob.Site.Models.Rent obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAluguelController/Editar", ReplyAction="http://tempuri.org/IAluguelController/EditarResponse")]
        System.Threading.Tasks.Task<Imob.Site.Models.Rent> EditarAsync(Imob.Site.Models.Rent obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAluguelController/Excluir", ReplyAction="http://tempuri.org/IAluguelController/ExcluirResponse")]
        Imob.Site.Models.Rent Excluir(Imob.Site.Models.Rent obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAluguelController/Excluir", ReplyAction="http://tempuri.org/IAluguelController/ExcluirResponse")]
        System.Threading.Tasks.Task<Imob.Site.Models.Rent> ExcluirAsync(Imob.Site.Models.Rent obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAluguelControllerChannel : Imob.View.AluguelController.IAluguelController, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AluguelControllerClient : System.ServiceModel.ClientBase<Imob.View.AluguelController.IAluguelController>, Imob.View.AluguelController.IAluguelController {
        
        public AluguelControllerClient() {
        }
        
        public AluguelControllerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AluguelControllerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AluguelControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AluguelControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Imob.Site.Models.Rent Salvar(Imob.Site.Models.Rent obj) {
            return base.Channel.Salvar(obj);
        }
        
        public System.Threading.Tasks.Task<Imob.Site.Models.Rent> SalvarAsync(Imob.Site.Models.Rent obj) {
            return base.Channel.SalvarAsync(obj);
        }
        
        public Imob.Site.Models.Rent[] Obter() {
            return base.Channel.Obter();
        }
        
        public System.Threading.Tasks.Task<Imob.Site.Models.Rent[]> ObterAsync() {
            return base.Channel.ObterAsync();
        }
        
        public string[] ObterIdEInquilinos() {
            return base.Channel.ObterIdEInquilinos();
        }
        
        public System.Threading.Tasks.Task<string[]> ObterIdEInquilinosAsync() {
            return base.Channel.ObterIdEInquilinosAsync();
        }
        
        public Imob.Site.Models.Rent Editar(Imob.Site.Models.Rent obj) {
            return base.Channel.Editar(obj);
        }
        
        public System.Threading.Tasks.Task<Imob.Site.Models.Rent> EditarAsync(Imob.Site.Models.Rent obj) {
            return base.Channel.EditarAsync(obj);
        }
        
        public Imob.Site.Models.Rent Excluir(Imob.Site.Models.Rent obj) {
            return base.Channel.Excluir(obj);
        }
        
        public System.Threading.Tasks.Task<Imob.Site.Models.Rent> ExcluirAsync(Imob.Site.Models.Rent obj) {
            return base.Channel.ExcluirAsync(obj);
        }
    }
}
