//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imob.View.ClienteController {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClienteController.IClienteController")]
    public interface IClienteController {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteController/Salvar", ReplyAction="http://tempuri.org/IClienteController/SalvarResponse")]
        Imob.Site.Models.Customer Salvar(Imob.Site.Models.Customer obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteController/Salvar", ReplyAction="http://tempuri.org/IClienteController/SalvarResponse")]
        System.Threading.Tasks.Task<Imob.Site.Models.Customer> SalvarAsync(Imob.Site.Models.Customer obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteControllerChannel : Imob.View.ClienteController.IClienteController, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteControllerClient : System.ServiceModel.ClientBase<Imob.View.ClienteController.IClienteController>, Imob.View.ClienteController.IClienteController {
        
        public ClienteControllerClient() {
        }
        
        public ClienteControllerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteControllerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Imob.Site.Models.Customer Salvar(Imob.Site.Models.Customer obj) {
            return base.Channel.Salvar(obj);
        }
        
        public System.Threading.Tasks.Task<Imob.Site.Models.Customer> SalvarAsync(Imob.Site.Models.Customer obj) {
            return base.Channel.SalvarAsync(obj);
        }
    }
}
