//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imob.View.PropriedadeController {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PropriedadeController.IPropriedadeController")]
    public interface IPropriedadeController {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPropriedadeController/Salvar", ReplyAction="http://tempuri.org/IPropriedadeController/SalvarResponse")]
        Imob.Site.Models.Habitation Salvar(Imob.Site.Models.Habitation obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPropriedadeController/Salvar", ReplyAction="http://tempuri.org/IPropriedadeController/SalvarResponse")]
        System.Threading.Tasks.Task<Imob.Site.Models.Habitation> SalvarAsync(Imob.Site.Models.Habitation obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPropriedadeController/Obter", ReplyAction="http://tempuri.org/IPropriedadeController/ObterResponse")]
        Imob.Site.Models.Habitation[] Obter();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPropriedadeController/Obter", ReplyAction="http://tempuri.org/IPropriedadeController/ObterResponse")]
        System.Threading.Tasks.Task<Imob.Site.Models.Habitation[]> ObterAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPropriedadeController/Editar", ReplyAction="http://tempuri.org/IPropriedadeController/EditarResponse")]
        Imob.Site.Models.Habitation Editar(Imob.Site.Models.Habitation obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPropriedadeController/Editar", ReplyAction="http://tempuri.org/IPropriedadeController/EditarResponse")]
        System.Threading.Tasks.Task<Imob.Site.Models.Habitation> EditarAsync(Imob.Site.Models.Habitation obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPropriedadeController/Excluir", ReplyAction="http://tempuri.org/IPropriedadeController/ExcluirResponse")]
        Imob.Site.Models.Habitation Excluir(Imob.Site.Models.Habitation obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPropriedadeController/Excluir", ReplyAction="http://tempuri.org/IPropriedadeController/ExcluirResponse")]
        System.Threading.Tasks.Task<Imob.Site.Models.Habitation> ExcluirAsync(Imob.Site.Models.Habitation obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPropriedadeControllerChannel : Imob.View.PropriedadeController.IPropriedadeController, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PropriedadeControllerClient : System.ServiceModel.ClientBase<Imob.View.PropriedadeController.IPropriedadeController>, Imob.View.PropriedadeController.IPropriedadeController {
        
        public PropriedadeControllerClient() {
        }
        
        public PropriedadeControllerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PropriedadeControllerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PropriedadeControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PropriedadeControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Imob.Site.Models.Habitation Salvar(Imob.Site.Models.Habitation obj) {
            return base.Channel.Salvar(obj);
        }
        
        public System.Threading.Tasks.Task<Imob.Site.Models.Habitation> SalvarAsync(Imob.Site.Models.Habitation obj) {
            return base.Channel.SalvarAsync(obj);
        }
        
        public Imob.Site.Models.Habitation[] Obter() {
            return base.Channel.Obter();
        }
        
        public System.Threading.Tasks.Task<Imob.Site.Models.Habitation[]> ObterAsync() {
            return base.Channel.ObterAsync();
        }
        
        public Imob.Site.Models.Habitation Editar(Imob.Site.Models.Habitation obj) {
            return base.Channel.Editar(obj);
        }
        
        public System.Threading.Tasks.Task<Imob.Site.Models.Habitation> EditarAsync(Imob.Site.Models.Habitation obj) {
            return base.Channel.EditarAsync(obj);
        }
        
        public Imob.Site.Models.Habitation Excluir(Imob.Site.Models.Habitation obj) {
            return base.Channel.Excluir(obj);
        }
        
        public System.Threading.Tasks.Task<Imob.Site.Models.Habitation> ExcluirAsync(Imob.Site.Models.Habitation obj) {
            return base.Channel.ExcluirAsync(obj);
        }
    }
}
