//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imob.View.ProprietarioController {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProprietarioController.IProprietarioController")]
    public interface IProprietarioController {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProprietarioController/Salvar", ReplyAction="http://tempuri.org/IProprietarioController/SalvarResponse")]
        Imob.Site.Models.Owner Salvar(Imob.Site.Models.Owner obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProprietarioController/Salvar", ReplyAction="http://tempuri.org/IProprietarioController/SalvarResponse")]
        System.Threading.Tasks.Task<Imob.Site.Models.Owner> SalvarAsync(Imob.Site.Models.Owner obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProprietarioController/Obter", ReplyAction="http://tempuri.org/IProprietarioController/ObterResponse")]
        Imob.Site.Models.Owner[] Obter();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProprietarioController/Obter", ReplyAction="http://tempuri.org/IProprietarioController/ObterResponse")]
        System.Threading.Tasks.Task<Imob.Site.Models.Owner[]> ObterAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProprietarioController/ObterPorId", ReplyAction="http://tempuri.org/IProprietarioController/ObterPorIdResponse")]
        Imob.Site.Models.Owner ObterPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProprietarioController/ObterPorId", ReplyAction="http://tempuri.org/IProprietarioController/ObterPorIdResponse")]
        System.Threading.Tasks.Task<Imob.Site.Models.Owner> ObterPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProprietarioController/Editar", ReplyAction="http://tempuri.org/IProprietarioController/EditarResponse")]
        Imob.Site.Models.Owner Editar(Imob.Site.Models.Owner obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProprietarioController/Editar", ReplyAction="http://tempuri.org/IProprietarioController/EditarResponse")]
        System.Threading.Tasks.Task<Imob.Site.Models.Owner> EditarAsync(Imob.Site.Models.Owner obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProprietarioController/Excluir", ReplyAction="http://tempuri.org/IProprietarioController/ExcluirResponse")]
        Imob.Site.Models.Owner Excluir(Imob.Site.Models.Owner obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProprietarioController/Excluir", ReplyAction="http://tempuri.org/IProprietarioController/ExcluirResponse")]
        System.Threading.Tasks.Task<Imob.Site.Models.Owner> ExcluirAsync(Imob.Site.Models.Owner obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProprietarioControllerChannel : Imob.View.ProprietarioController.IProprietarioController, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProprietarioControllerClient : System.ServiceModel.ClientBase<Imob.View.ProprietarioController.IProprietarioController>, Imob.View.ProprietarioController.IProprietarioController {
        
        public ProprietarioControllerClient() {
        }
        
        public ProprietarioControllerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProprietarioControllerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProprietarioControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProprietarioControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Imob.Site.Models.Owner Salvar(Imob.Site.Models.Owner obj) {
            return base.Channel.Salvar(obj);
        }
        
        public System.Threading.Tasks.Task<Imob.Site.Models.Owner> SalvarAsync(Imob.Site.Models.Owner obj) {
            return base.Channel.SalvarAsync(obj);
        }
        
        public Imob.Site.Models.Owner[] Obter() {
            return base.Channel.Obter();
        }
        
        public System.Threading.Tasks.Task<Imob.Site.Models.Owner[]> ObterAsync() {
            return base.Channel.ObterAsync();
        }
        
        public Imob.Site.Models.Owner ObterPorId(int id) {
            return base.Channel.ObterPorId(id);
        }
        
        public System.Threading.Tasks.Task<Imob.Site.Models.Owner> ObterPorIdAsync(int id) {
            return base.Channel.ObterPorIdAsync(id);
        }
        
        public Imob.Site.Models.Owner Editar(Imob.Site.Models.Owner obj) {
            return base.Channel.Editar(obj);
        }
        
        public System.Threading.Tasks.Task<Imob.Site.Models.Owner> EditarAsync(Imob.Site.Models.Owner obj) {
            return base.Channel.EditarAsync(obj);
        }
        
        public Imob.Site.Models.Owner Excluir(Imob.Site.Models.Owner obj) {
            return base.Channel.Excluir(obj);
        }
        
        public System.Threading.Tasks.Task<Imob.Site.Models.Owner> ExcluirAsync(Imob.Site.Models.Owner obj) {
            return base.Channel.ExcluirAsync(obj);
        }
    }
}
