//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imob.View.PagamentoController {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PagamentoController.IPagamentoController")]
    public interface IPagamentoController {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoController/Salvar", ReplyAction="http://tempuri.org/IPagamentoController/SalvarResponse")]
        Imob.Site.Models.Payment Salvar(Imob.Site.Models.Payment obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoController/Salvar", ReplyAction="http://tempuri.org/IPagamentoController/SalvarResponse")]
        System.Threading.Tasks.Task<Imob.Site.Models.Payment> SalvarAsync(Imob.Site.Models.Payment obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoController/Obter", ReplyAction="http://tempuri.org/IPagamentoController/ObterResponse")]
        Imob.Site.Models.Payment[] Obter();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoController/Obter", ReplyAction="http://tempuri.org/IPagamentoController/ObterResponse")]
        System.Threading.Tasks.Task<Imob.Site.Models.Payment[]> ObterAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoController/Editar", ReplyAction="http://tempuri.org/IPagamentoController/EditarResponse")]
        Imob.Site.Models.Payment Editar(Imob.Site.Models.Payment obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoController/Editar", ReplyAction="http://tempuri.org/IPagamentoController/EditarResponse")]
        System.Threading.Tasks.Task<Imob.Site.Models.Payment> EditarAsync(Imob.Site.Models.Payment obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoController/Excluir", ReplyAction="http://tempuri.org/IPagamentoController/ExcluirResponse")]
        Imob.Site.Models.Payment Excluir(Imob.Site.Models.Payment obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoController/Excluir", ReplyAction="http://tempuri.org/IPagamentoController/ExcluirResponse")]
        System.Threading.Tasks.Task<Imob.Site.Models.Payment> ExcluirAsync(Imob.Site.Models.Payment obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPagamentoControllerChannel : Imob.View.PagamentoController.IPagamentoController, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PagamentoControllerClient : System.ServiceModel.ClientBase<Imob.View.PagamentoController.IPagamentoController>, Imob.View.PagamentoController.IPagamentoController {
        
        public PagamentoControllerClient() {
        }
        
        public PagamentoControllerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PagamentoControllerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagamentoControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagamentoControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Imob.Site.Models.Payment Salvar(Imob.Site.Models.Payment obj) {
            return base.Channel.Salvar(obj);
        }
        
        public System.Threading.Tasks.Task<Imob.Site.Models.Payment> SalvarAsync(Imob.Site.Models.Payment obj) {
            return base.Channel.SalvarAsync(obj);
        }
        
        public Imob.Site.Models.Payment[] Obter() {
            return base.Channel.Obter();
        }
        
        public System.Threading.Tasks.Task<Imob.Site.Models.Payment[]> ObterAsync() {
            return base.Channel.ObterAsync();
        }
        
        public Imob.Site.Models.Payment Editar(Imob.Site.Models.Payment obj) {
            return base.Channel.Editar(obj);
        }
        
        public System.Threading.Tasks.Task<Imob.Site.Models.Payment> EditarAsync(Imob.Site.Models.Payment obj) {
            return base.Channel.EditarAsync(obj);
        }
        
        public Imob.Site.Models.Payment Excluir(Imob.Site.Models.Payment obj) {
            return base.Channel.Excluir(obj);
        }
        
        public System.Threading.Tasks.Task<Imob.Site.Models.Payment> ExcluirAsync(Imob.Site.Models.Payment obj) {
            return base.Channel.ExcluirAsync(obj);
        }
    }
}
