//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imob.View.TaxaController {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaxaController.ITaxaController")]
    public interface ITaxaController {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxaController/Salvar", ReplyAction="http://tempuri.org/ITaxaController/SalvarResponse")]
        Imob.Site.Models.Fee Salvar(Imob.Site.Models.Fee obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxaController/Salvar", ReplyAction="http://tempuri.org/ITaxaController/SalvarResponse")]
        System.Threading.Tasks.Task<Imob.Site.Models.Fee> SalvarAsync(Imob.Site.Models.Fee obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxaController/Obter", ReplyAction="http://tempuri.org/ITaxaController/ObterResponse")]
        Imob.Site.Models.Fee[] Obter();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxaController/Obter", ReplyAction="http://tempuri.org/ITaxaController/ObterResponse")]
        System.Threading.Tasks.Task<Imob.Site.Models.Fee[]> ObterAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxaController/Editar", ReplyAction="http://tempuri.org/ITaxaController/EditarResponse")]
        Imob.Site.Models.Fee Editar(Imob.Site.Models.Fee obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxaController/Editar", ReplyAction="http://tempuri.org/ITaxaController/EditarResponse")]
        System.Threading.Tasks.Task<Imob.Site.Models.Fee> EditarAsync(Imob.Site.Models.Fee obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxaController/Excluir", ReplyAction="http://tempuri.org/ITaxaController/ExcluirResponse")]
        Imob.Site.Models.Fee Excluir(Imob.Site.Models.Fee obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxaController/Excluir", ReplyAction="http://tempuri.org/ITaxaController/ExcluirResponse")]
        System.Threading.Tasks.Task<Imob.Site.Models.Fee> ExcluirAsync(Imob.Site.Models.Fee obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITaxaControllerChannel : Imob.View.TaxaController.ITaxaController, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaxaControllerClient : System.ServiceModel.ClientBase<Imob.View.TaxaController.ITaxaController>, Imob.View.TaxaController.ITaxaController {
        
        public TaxaControllerClient() {
        }
        
        public TaxaControllerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaxaControllerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaxaControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaxaControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Imob.Site.Models.Fee Salvar(Imob.Site.Models.Fee obj) {
            return base.Channel.Salvar(obj);
        }
        
        public System.Threading.Tasks.Task<Imob.Site.Models.Fee> SalvarAsync(Imob.Site.Models.Fee obj) {
            return base.Channel.SalvarAsync(obj);
        }
        
        public Imob.Site.Models.Fee[] Obter() {
            return base.Channel.Obter();
        }
        
        public System.Threading.Tasks.Task<Imob.Site.Models.Fee[]> ObterAsync() {
            return base.Channel.ObterAsync();
        }
        
        public Imob.Site.Models.Fee Editar(Imob.Site.Models.Fee obj) {
            return base.Channel.Editar(obj);
        }
        
        public System.Threading.Tasks.Task<Imob.Site.Models.Fee> EditarAsync(Imob.Site.Models.Fee obj) {
            return base.Channel.EditarAsync(obj);
        }
        
        public Imob.Site.Models.Fee Excluir(Imob.Site.Models.Fee obj) {
            return base.Channel.Excluir(obj);
        }
        
        public System.Threading.Tasks.Task<Imob.Site.Models.Fee> ExcluirAsync(Imob.Site.Models.Fee obj) {
            return base.Channel.ExcluirAsync(obj);
        }
    }
}
